apiVersion: v1
kind: Service
metadata:
  name: py-go-app-service
  namespace: otus
spec:
  selector:
    app: py-go-app
  ports:
  - name: flask-port
    port: 3000
    targetPort: 3000
  - name: go-port
    port: 8080
    targetPort: 8080
  type: ClusterIP
